'use client';

import React from 'react';
import LogPage from '../../../components/LogPage';

export default function ActivityLogs() {
  // DUMMY ONLY – REMOVE IN PRODUCTION
  const logs = [
    {
      id: 1,
      timestamp: "2025-01-19 10:30:45",
      admin: "John Admin",
      userId: "admin-001",
      action: "Approved ID Application",
      target: "APP-12345 (Jane Doe - National ID)",
      entityType: "application",
      ipAddress: "192.168.1.105",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      level: "info",
      message: "Approved National ID application after document verification",
      location: "Lagos, Country",
    },
    {
      id: 2,
      timestamp: "2025-01-19 10:25:12",
      admin: "Sarah Manager",
      userId: "admin-002",
      action: "Suspended User Account",
      target: "user-67890 (Michael Johnson)",
      entityType: "user",
      ipAddress: "192.168.1.108",
      userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
      level: "warning",
      message: "Account suspended due to suspicious activity",
      location: "Abuja, Country",
    },
    {
      id: 3,
      timestamp: "2025-01-19 10:20:33",
      admin: "Mike Reviewer",
      userId: "admin-003",
      action: "Updated News Article",
      target: "news-456 (Health Insurance Update)",
      entityType: "news",
      ipAddress: "192.168.1.112",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      level: "info",
      message: "Updated health insurance benefit information",
      location: "Port Harcourt, Country",
    },
    {
      id: 4,
      timestamp: "2025-01-19 10:15:22",
      admin: "Admin Support",
      userId: "admin-004",
      action: "Resolved Complaint",
      target: "COMP-789 (Application Delay)",
      entityType: "complaint",
      ipAddress: "192.168.1.115",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      level: "info",
      message: "Resolved complaint about delayed application processing",
      location: "Kano, Country",
    },
    {
      id: 5,
      timestamp: "2025-01-19 10:10:15",
      admin: "Unknown",
      userId: "unknown",
      action: "Failed Login Attempt",
      target: "admin-login",
      entityType: "authentication",
      ipAddress: "203.45.67.89",
      userAgent: "Mozilla/5.0 (Linux; Android 10)",
      level: "error",
      message: "Multiple failed login attempts - potential security threat",
      location: "Unknown Location",
    },
    {
      id: 6,
      timestamp: "2025-01-19 10:05:44",
      admin: "Lisa Admin",
      userId: "admin-005",
      action: "Created Election",
      target: "election-2025-gov (Governmental Election)",
      entityType: "election",
      ipAddress: "192.168.1.120",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      level: "info",
      message: "Created new governmental election for Lagos State",
      location: "Lagos, Country",
    },
    {
      id: 7,
      timestamp: "2025-01-19 09:58:31",
      admin: "Super Admin",
      userId: "superadmin-001",
      action: "Modified System Settings",
      target: "system-config",
      entityType: "system",
      ipAddress: "192.168.1.100",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      level: "warning",
      message: "Updated branding and notification settings",
      location: "Abuja, Country",
    },
    {
      id: 8,
      timestamp: "2025-01-19 09:55:17",
      admin: "David Viewer",
      userId: "admin-006",
      action: "Exported Report",
      target: "report-monthly-stats",
      entityType: "report",
      ipAddress: "192.168.1.125",
      userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
      level: "info",
      message: "Generated and exported monthly statistics report",
      location: "Ibadan, Country",
    },
    {
      id: 9,
      timestamp: "2025-01-19 10:40:00",
      admin: "Super Admin",
      userId: "superadmin-001",
      action: "Created New Admin Account",
      target: "admin-007 (New Admin User)",
      entityType: "admin_management",
      ipAddress: "192.168.1.100",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      level: "info",
      message: "Super Admin created a new admin account for New Admin User",
      location: "Abuja, Country",
    },
    {
      id: 10,
      timestamp: "2025-01-19 10:45:00",
      admin: "Super Admin",
      userId: "superadmin-001",
      action: "Reset Admin Password",
      target: "admin-002 (Sarah Manager)",
      entityType: "admin_management",
      ipAddress: "192.168.1.100",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      level: "warning",
      message: "Super Admin reset password for Sarah Manager, force reset on next login enabled",
      location: "Abuja, Country",
    },
    {
      id: 11,
      timestamp: "2025-01-19 10:50:00",
      admin: "John Admin",
      userId: "admin-001",
      action: "Changed Own Password",
      target: "admin-001 (John Admin)",
      entityType: "authentication",
      ipAddress: "192.168.1.105",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      level: "info",
      message: "Admin John Admin changed their own password after temporary login",
      location: "Lagos, Country",
    },
  ];

  const stats = {
    totalLogs: 11,
    errorLogs: 1,
    warningLogs: 2,
    infoLogs: 8,
    todayLogs: 11
  };

  return (
    <LogPage
      logs={logs}
      stats={stats}
      title="Admin Activity Logs"
      dataSource="admin"
    />
  );
}
